#!/usr/bin/env bash
# Builds libmagic.so + the Magdir fragment set from an upstream file/file
# release and stages both into src/libmagic/.
#
# Which upstream version gets built is a choice for whoever runs this
# script, not something baked in once for everyone -- pass a tag to build
# a different one:
#
#   scripts/build-lib.sh FILE5_46
#
# With no argument, DEFAULT_FILE_VERSION below is used. That default is
# the version this repo's own CI builds and tests; bump it deliberately
# when adopting a new one, that one-line change is the whole procedure for
# moving the default forward.
#
# Usage: scripts/build-lib.sh [file-tag]
set -euo pipefail

DEFAULT_FILE_VERSION="FILE5_48"
FILE_VERSION="${1:-$DEFAULT_FILE_VERSION}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

git clone --quiet --branch "$FILE_VERSION" --depth 1 \
    https://github.com/file/file.git "$BUILD_DIR/file-src"
cd "$BUILD_DIR/file-src"

autoreconf -fiv
./configure \
    --prefix="$BUILD_DIR/install" \
    --libdir="$BUILD_DIR/install/lib64" \
    --enable-shared --disable-static
make -j"$(nproc)"
make check

PKG_DIR="$REPO_ROOT/src/libmagic"
DATA_DIR="$PKG_DIR/data"
# data/__init__.py is committed (makes data/ a real subpackage, see the
# README) -- clear only the generated contents underneath it, never the
# directory itself.
rm -rf "$DATA_DIR/magdir" "$DATA_DIR/libmagic.so.1" "$DATA_DIR/default.mgc"
mkdir -p "$DATA_DIR/magdir"

cp src/.libs/libmagic.so.1.0.0 "$DATA_DIR/libmagic.so.1"
chmod 755 "$DATA_DIR/libmagic.so.1"
cp magic/Magdir/* magic/Header magic/Localstuff "$DATA_DIR/magdir/"
cp COPYING "$REPO_ROOT/LICENSE.file-upstream"

# The unmodified-Magdir .mgc that `make` already produces as a build
# byproduct (magic/Makefile.am's own compile rule) -- reused as-is rather
# than recompiled, so this is guaranteed identical to what upstream's own
# build produces. Only for development/debugging via `libmagic-wheel
# classify` without a prior `compile` step; real deployments compile their
# own combined .mgc with their own overrides via compile_database().
cp magic/magic.mgc "$DATA_DIR/default.mgc"

# Exposed at runtime as libmagic.UPSTREAM_VERSION -- this package's own
# version (pyproject.toml) tracks its own code, deliberately not this. See
# the README for why the two are kept independent.
UPSTREAM_VERSION="${FILE_VERSION#FILE}"
UPSTREAM_VERSION="${UPSTREAM_VERSION/_/.}"
cat > "$PKG_DIR/_upstream_version.py" <<EOF
"""Generated by scripts/build-lib.sh -- do not edit by hand."""

UPSTREAM_VERSION = "$UPSTREAM_VERSION"
EOF

echo "built $FILE_VERSION (upstream version $UPSTREAM_VERSION) -> $PKG_DIR"
